# Решение системы уравнений методом Гаусса

### В рамках данной задачи нам нужно будет работать со строками матрицы, их мы будем реализовавать через списки

In [1]:
import numpy as np

In [62]:
a = [1,2,3]
b = [4,5,6]

In [19]:
#Сначала нам нужно написать две функции, которые будут складывать и умножать 
#Наши векторы на скаляры 

In [64]:
def mult_2(a):
    answer = 2 * a
    return answer

print(mult_2(3))

6


In [65]:
def add_vectors(vec1, vec2):
    '''
    Функция складывает два вектора одинаковой длины
    '''

    #Убедимся, что длины векторов равны
    assert len(vec1) == len(vec2), 'Длины векторов не равны'

    answer = list() #Создадим список, куда будем заносить значения

    for i in range(0, len(vec1)):
        answer.append(vec1[i]+vec2[i])
    
    return answer

In [74]:
lst = [1,2,3]

lst[2]

3

In [21]:
def mult_vector(vec, number):
    '''
    Функция умножает вектор vеc, на скаляр number
    '''    
    answer = [i*number for i in vec]
    
    return answer

In [22]:
print(add_vectors(a,b))

[5, 7, 9]


In [23]:
print(mult_vector(a, 2))

[2, 4, 6]


In [100]:
import numpy as np

def Gauss(matrix, info=False):
    '''
    Решение системы уравнений методом Гаусса
    info = False (default).
    Если info = True, выводится больше информации
    об обратном ходе Гаусса
    Matrix – матрица коэффициентов и свободных членов (np.array)
    '''

    #Проверим, что у матрицы существует решение, притом единственное

    #system1 – матрица коэффициентов
    system1 = np.array(
        [line[:-1] for line in matrix]
                       )
    
    det = np.linalg.det(system1)

    if np.abs(det) < 10**(-5):
        return 'Система не является определённой. Решений нет или бесконечно много'


    n = len(matrix) #Число строк в матрице
    
    matrix = matrix.astype(float)  # convert to float type
    
    # Прямой ход метода Гаусса
    for i in range(n-1):
        
        #(для первой итерации) из первой строки вычитаем нулевую
        #потом из второй стоки вычитаем нулевую
        #if info == True:
        #    print('Матрица на входе во внутренний цикл')
        #    print(matrix)


        for j in range(i+1, n):

            # Вычисляем множитель, на который будем умножать i-ую строку
            # при вычитании ее из j-ой строки
            factor = matrix[j,i] / matrix[i,i]
            # Вычитаем i-ую строку, умноженную на factor, из j-ой строки
            matrix[j] = matrix[j] - factor * matrix[i]

        #if info == True:
        #    print('После внутреннего цикла')
        #    print(matrix)

    if info == True:   
    #Посмотрим на получившуюся матрицу
        print(matrix)


    
    # Обратный ход метода Гаусса
    x = np.zeros(n)

    #Цикл от n-1 до 0 (включительно) с шагом -1
    #Идём от последней строчки в диагонализованной матрицы к первой
    for i in range(n-1, -1, -1): 
        # Вычисляем значение i-ой неизвестной

        #Для детального анализа
        if info == True:
            print('', f'i = {i}', f'x = {x}', f'matrix[i,:n] = {matrix[i,:n]}', f'np.dot = {np.dot(matrix[i,:n], x)}', '', sep='\n')

        #       (Значение свободного члена - скалярное произведение) / коэффициент при переменной
        x[i] = (matrix[i,n] - np.dot(matrix[i,:n], x)) / matrix[i,i]
        #При первой итерации цикла np.dot(*) = 0

    return x

# Example usage:
equation = np.array([
            [3, 2, -5, -1],
            [2, -1, 3, 13],
            [1, 2, -1, 9]])


print(Gauss(equation, info=True))

[[ 3.00000000e+00  2.00000000e+00 -5.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -2.33333333e+00  6.33333333e+00  1.36666667e+01]
 [ 0.00000000e+00 -2.22044605e-16  4.28571429e+00  1.71428571e+01]]

i = 2
x = [0. 0. 0.]
matrix[i,:n] = [ 0.00000000e+00 -2.22044605e-16  4.28571429e+00]
np.dot = 0.0


i = 1
x = [0. 0. 4.]
matrix[i,:n] = [ 0.         -2.33333333  6.33333333]
np.dot = 25.333333333333332


i = 0
x = [0. 5. 4.]
matrix[i,:n] = [ 3.  2. -5.]
np.dot = -10.0

[3. 5. 4.]


In [98]:
equation = np.array(
                    [
                    [3, 2, -5, -1],
                    [2, -1, 3, 13],
                    [1, 2, -1, 9]
                    ]
                    )

system1 = np.array(
    [line[:-1] for line in equation]
                    )

#np.linalg.det(system1)


equation[0,:2]

array([3, 2])

\begin{bmatrix}
1 & 2 & -1 & 9 \\
0 & 1 & -1 & 1 \\
0 & 0 & 3 & 12
\end{bmatrix}

$$ x = 9 - (-1)*z - 2 * (y)$$
$$ x = 9 - (-1,2) * (z,y) $$



In [53]:
#Проверим наше решение
system = np.array(
                  [
                    [1,2,3,4],
                    [5,6,7,8],
                    [1,2,3,4]
                  ]
)

print(Gauss(system))



Система не является определённой. Решений нет или бесконечно много


In [51]:
A = np.array(
    [
        [1,2,3],
        [5,6,7],
        [1,2,3]
    ]
)
a = np.linalg.det(A)

if np.abs(a) < np.power(10.0, -5):
    print('ejal')

ejal


In [26]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
A[1,:2]

array([4, 5])

In [21]:
system = np.array(
                  [
                        [1,1,1,0],
                        [8,4,6,8],
                        [15,3,5,0]
                  ]
                 )
Gauss(system)

[[  1.   1.   1.   0.]
 [  0.  -4.  -2.   8.]
 [  0.   0.  -4. -24.]]

i = 2
x = [0. 0. 0.]
matrix[i,:n] = [ 0.  0. -4.]
np.dot = 0.0


i = 1
x = [0. 0. 6.]
matrix[i,:n] = [ 0. -4. -2.]
np.dot = -12.0


i = 0
x = [ 0. -5.  6.]
matrix[i,:n] = [1. 1. 1.]
np.dot = 1.0



array([-1., -5.,  6.])

In [28]:
#Для проверки решения через sympy


import numpy as np
from scipy import linalg


a = np.array(
            [
                [3, 2, 0], 
                [1, -1, 0], 
                [0, 5, 1]
            ]
            )

b = np.array(
            [2,
             4, 
            -1]
             )
#x = linalg.solve(a, b)

#np.dot(a, x) == b
linalg.solve(a, b)

array([ 2., -2.,  9.])

In [112]:
#Дело за малым – прочитать из файла 

with open('numbers.txt', 'r') as f:
    content = [i.replace('\n', '') for i in f.readlines()]

content

num_of_eq = int(content[0])


our_matrix = list()

#Пробегаем циклом по строчкам (исключая нулевую строку)
for k in range(1, num_of_eq+1):
    #      превращ. в целочисленое знач.     #делит string на список 
    lst = [int(number) for number in content[k].split()] #[ 3,  2, -5, -1]

    #объединим в список списоков
    our_matrix.append(lst)

np.array(our_matrix)

array([[ 3,  2, -5, -1],
       [ 2, -1,  3, 13],
       [ 1,  2, -1,  9]])